// ng/src/app/pages/onboarding/onboarding.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { LanguageService } from '../../core/services/language.service';

interface OnboardingStep {
  number: number;
  icon: string;
  title: string;
  description: string;
  bgColor: string;
  borderColor: string;
  action: () => void;
}

@Component({
  selector: 'app-onboarding',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './onboarding.component.html',
  styleUrl: './onboarding.component.sass'
})
export class OnboardingComponent {
  completedSteps: number[] = [];

  steps: OnboardingStep[] = [
    {
      number: 1,
      icon: 'user',
      title: 'צרו את הפרופיל שלכם',
      description: 'ספרו לנו מי אתם, מה העסק שלכם, ומה הסגנון שמתאים לכם – ככה iHoogi תדע לבנות עבורכם חוויה שיווקית מותאמת אישית. 💡',
      bgColor: 'from-blue-50 to-cyan-50',
      borderColor: 'border-blue-200',
      action: () => this.router.navigate(['/profile'])
    },
    {
      number: 2,
      icon: 'file-text',
      title: 'צרו שאלון חכם שמכין אתכם למכירה ממוקדת',
      description: 'השאלון הופך את המתעניינים ללידים חמים – הוא שואל, ממקד ומאפשר לכם להגיע לשיחת המכירה כשאתם כבר צעד אחד קדימה. 🎯',
      bgColor: 'from-purple-50 to-pink-50',
      borderColor: 'border-purple-200',
      action: () => this.router.navigate(['/dashboard'])
    },
    {
      number: 3,
      icon: 'message-square',
      title: 'צרו תבנית מענה ללקוח',
      description: 'הגדירו איך iHoogi תדבר בשם העסק שלכם – באופן מקצועי, אישי ואוטומטי, שמייצר אמון וחיבור אמיתי עם הלקוח. 💬',
      bgColor: 'from-orange-50 to-red-50',
      borderColor: 'border-orange-200',
      action: () => this.router.navigate(['/questionnaires/new'])
    },
    {
      number: 4,
      icon: 'share',
      title: 'קבלו את הלינק שלכם לשיתוף',
      description: 'בחרו איך תרצו שהלקוחות ימלאו את השאלון: כ־צ\'אט אינטראקטיבי, טופס חכם, או קוד QR לסריקה – רק תבחרו, ושתפו בכל מקום שתרצו: וואטסאפ, אתר או רשתות חברתיות. 🚀',
      bgColor: 'from-green-50 to-teal-50',
      borderColor: 'border-green-200',
      action: () => this.router.navigate(['/distribution-hub'])
    }
  ];

  constructor(
    private router: Router,
    public lang: LanguageService
  ) {}

  handleStepClick(stepNumber: number, action: () => void) {
    if (!this.completedSteps.includes(stepNumber)) {
      this.completedSteps = [...this.completedSteps, stepNumber];
    }
    action();
  }

  handleStart() {
    // Mark onboarding as completed and go to profile
    localStorage.setItem('onboarding_completed', 'true');
    this.router.navigate(['/profile']);
  }

  isCompleted(stepNumber: number): boolean {
    return this.completedSteps.includes(stepNumber);
  }
}

<div class="onboarding-container" dir="rtl">
  <div class="container">
    <!-- Header with iHoogi logo -->
    <div class="header">
      <div class="logo-animation">
        <img src="/img/logo.png" alt="iHoogi Avatar" class="avatar" />
      </div>
      <h1 class="title">ברוכים הבאים ל־iHoogi</h1>
      <p class="subtitle">
        המערכת שמדברת עם הלקוחות שלכם, מתזכרת אותם,
        ומוודאת שאף ליד לא מתפספס בדרך.
        בואו נתחיל – זה קל, מהיר, וחכם. ⚡
      </p>
      <h2 class="steps-title">✨ הצעדים הראשונים שלכם עם iHoogi</h2>
    </div>

    <!-- Steps -->
    <div class="steps-container">
      @for (step of steps; track step.number) {
        <div
          class="step-card"
          [class.completed]="isCompleted(step.number)"
          (click)="handleStepClick(step.number, step.action)">
          <div class="step-content">
            <!-- Number Badge -->
            <div class="step-badge">
              @if (isCompleted(step.number)) {
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                  <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path>
                  <polyline points="22 4 12 14.01 9 11.01"></polyline>
                </svg>
              } @else {
                <span class="step-number">{{ step.number }}</span>
              }
            </div>

            <!-- Content -->
            <div class="step-text">
              <div class="step-header">
                @if (step.icon === 'user') {
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
                    <circle cx="12" cy="7" r="4"></circle>
                  </svg>
                } @else if (step.icon === 'file-text') {
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
                    <polyline points="14 2 14 8 20 8"></polyline>
                    <line x1="16" y1="13" x2="8" y2="13"></line>
                    <line x1="16" y1="17" x2="8" y2="17"></line>
                    <polyline points="10 9 9 9 8 9"></polyline>
                  </svg>
                } @else if (step.icon === 'message-square') {
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path>
                  </svg>
                } @else if (step.icon === 'share') {
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <circle cx="18" cy="5" r="3"></circle>
                    <circle cx="6" cy="12" r="3"></circle>
                    <circle cx="18" cy="19" r="3"></circle>
                    <line x1="8.59" y1="13.51" x2="15.42" y2="17.49"></line>
                    <line x1="15.41" y1="6.51" x2="8.59" y2="10.49"></line>
                  </svg>
                }
                <h3 class="step-title">{{ step.title }}</h3>
              </div>
              <p class="step-description">{{ step.description }}</p>
            </div>

            <!-- Arrow or Check -->
            <div class="step-arrow">
              @if (isCompleted(step.number)) {
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                  <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path>
                  <polyline points="22 4 12 14.01 9 11.01"></polyline>
                </svg>
              } @else {
                <span class="arrow">←</span>
              }
            </div>
          </div>
        </div>
      }
    </div>

    <!-- How it works section -->
    <div class="info-card">
      <div class="info-header">
        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"></polygon>
        </svg>
        <h2 class="info-title">🔁 ככה זה עובד בפשטות</h2>
      </div>
      <div class="info-flow">
        מילוי פרופיל → יצירת שאלון → בניית תבנית מענה ללקוח → קבלת הלינק
      </div>
      <div class="info-note">
        אתם מצרפים את הלקוחות –
      </div>
    </div>

    <!-- Bottom Section - "From here it's on us" -->
    <div class="info-card">
      <div class="info-header">
        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path>
        </svg>
        <h2 class="info-title">🤖 מכאן זה כבר עלינו</h2>
      </div>
      <p class="info-text">
        אנחנו נאסוף את הלידים, נרכז את כל המידע במקום אחד,
        נענה בשמכם, נתזכר את הלקוחות שלכם בדיוק ברגע הנכון –
        כדי שכל ליד יהפוך להזדמנות אמיתית. 🎯
      </p>
    </div>

    <!-- Action Button -->
    <div class="action-container">
      <button (click)="handleStart()" class="start-btn">
        בואו נתחיל! 🚀
      </button>
    </div>
  </div>
</div>

// Onboarding.tsx
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Sparkles, User, FileText, MessageSquare, Share2, Zap, CheckCircle2 } from "lucide-react";
import { useNavigate } from "react-router-dom";

const Onboarding = () => {
  const navigate = useNavigate();
  const [completedSteps, setCompletedSteps] = useState<number[]>([]);

  const steps = [
    {
      number: 1,
      icon: User,
      title: "צרו את הפרופיל שלכם",
      description: "ספרו לנו מי אתם, מה העסק שלכם, ומה הסגנון שמתאים לכם – ככה iHoogi תדע לבנות עבורכם חוויה שיווקית מותאמת אישית. 💡",
      bgColor: "from-blue-50 to-cyan-50",
      borderColor: "border-blue-200",
      action: () => navigate("/profile")
    },
    {
      number: 2,
      icon: FileText,
      title: "צרו שאלון חכם שמכין אתכם למכירה ממוקדת",
      description: "השאלון הופך את המתעניינים ללידים חמים – הוא שואל, ממקד ומאפשר לכם להגיע לשיחת המכירה כשאתם כבר צעד אחד קדימה. 🎯",
      bgColor: "from-purple-50 to-pink-50",
      borderColor: "border-purple-200",
      action: () => navigate("/my-hoogi")
    },
    {
      number: 3,
      icon: MessageSquare,
      title: "צרו תבנית מענה ללקוח",
      description: "הגדירו איך iHoogi תדבר בשם העסק שלכם – באופן מקצועי, אישי ואוטומטי, שמייצר אמון וחיבור אמיתי עם הלקוח. 💬",
      bgColor: "from-orange-50 to-red-50",
      borderColor: "border-orange-200",
      action: () => navigate("/create-template")
    },
    {
      number: 4,
      icon: Share2,
      title: "קבלו את הלינק שלכם לשיתוף",
      description: "בחרו איך תרצו שהלקוחות ימלאו את השאלון: כ־צ'אט אינטראקטיבי, טופס חכם, או קוד QR לסריקה – רק תבחרו, ושתפו בכל מקום שתרצו: וואטסאפ, אתר או רשתות חברתיות. 🚀",
      bgColor: "from-green-50 to-teal-50",
      borderColor: "border-green-200",
      action: () => navigate("/distribution")
    }
  ];

  const handleStepClick = (stepNumber: number, action: () => void) => {
    if (!completedSteps.includes(stepNumber)) {
      setCompletedSteps([...completedSteps, stepNumber]);
    }
    action();
  };

  const handleStart = () => {
    // Mark onboarding as completed and go to profile
    localStorage.setItem("onboarding_completed", "true");
    navigate("/profile");
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-background to-muted/20" dir="rtl">
      <div className="container mx-auto px-4 py-8 md:py-12">
        {/* Header with iHoogi logo */}
        <div className="text-center mb-8 md:mb-12">
          <div className="flex items-center justify-center gap-3 mb-6">
            <div className="w-20 h-20 md:w-24 md:h-24 rounded-full bg-primary/10 flex items-center justify-center shadow-lg animate-bounce">
              <img 
                src="/hoogi-new-avatar.png" 
                alt="iHoogi Avatar" 
                className="w-16 h-16 md:w-20 md:h-20 object-contain"
              />
            </div>
          </div>
          <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-primary to-primary/60 mb-4">
            ברוכים הבאים ל־iHoogi
          </h1>
          <p className="text-lg md:text-xl text-muted-foreground max-w-3xl mx-auto mb-6">
            המערכת שמדברת עם הלקוחות שלכם, מתזכרת אותם,
            ומוודאת שאף ליד לא מתפספס בדרך.
            בואו נתחיל – זה קל, מהיר, וחכם. ⚡
          </p>
          <h2 className="text-2xl md:text-3xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-primary to-primary/60 mb-6">
            ✨ הצעדים הראשונים שלכם עם iHoogi
          </h2>
        </div>

        {/* Steps */}
        <div className="max-w-4xl mx-auto space-y-4 md:space-y-6 mb-8">
          {steps.map((step) => {
            const StepIcon = step.icon;
            const isCompleted = completedSteps.includes(step.number);
            
            return (
              <Card 
                key={step.number}
                className={`border shadow-lg hover:shadow-xl transition-all duration-300 hover:-translate-y-1 cursor-pointer bg-gradient-to-l ${step.bgColor} ${step.borderColor} ${isCompleted ? 'border-primary' : 'hover:border-primary/50'}`}
                onClick={() => handleStepClick(step.number, step.action)}
              >
                <CardContent className="p-6 md:p-8">
                  <div className="flex items-start gap-4 md:gap-6">
                    {/* Number Badge */}
                    <div className={`flex-shrink-0 w-12 h-12 md:w-14 md:h-14 rounded-full bg-primary/10 flex items-center justify-center shadow-lg relative border border-primary/20`}>
                      {isCompleted ? (
                        <CheckCircle2 className="h-6 w-6 md:h-7 md:w-7 text-primary" />
                      ) : (
                        <span className="text-primary font-bold text-xl md:text-2xl">{step.number}</span>
                      )}
                    </div>

                    {/* Content */}
                    <div className="flex-1 text-right">
                      <div className="flex items-center gap-2 mb-2">
                        <StepIcon className="h-5 w-5 md:h-6 md:w-6 text-primary" />
                        <h3 className="text-xl md:text-2xl font-bold text-foreground">
                          {step.title}
                        </h3>
                      </div>
                      <p className="text-muted-foreground leading-relaxed text-sm md:text-base">
                        {step.description}
                      </p>
                    </div>

                    {/* Arrow or Check */}
                    <div className="flex-shrink-0">
                      {isCompleted ? (
                        <div className="w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center border border-primary/20">
                          <CheckCircle2 className="h-5 w-5 text-primary" />
                        </div>
                      ) : (
                        <div className="text-2xl text-muted-foreground">←</div>
                      )}
                    </div>
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>

        {/* How it works section */}
        <Card className="max-w-4xl mx-auto border shadow-lg bg-card/50 backdrop-blur-sm mb-8">
          <CardContent className="p-6 md:p-10 text-center">
            <div className="flex items-center justify-center gap-2 mb-4">
              <Zap className="h-8 w-8 text-primary" />
              <h2 className="text-2xl md:text-3xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-primary to-primary/60">
                🔁 ככה זה עובד בפשטות
              </h2>
            </div>
            <div className="text-muted-foreground leading-relaxed text-base md:text-lg max-w-3xl mx-auto mb-4">
              מילוי פרופיל → יצירת שאלון → בניית תבנית מענה ללקוח → קבלת הלינק
            </div>
            <div className="text-muted-foreground text-sm md:text-base">
              אתם מצרפים את הלקוחות –
            </div>
          </CardContent>
        </Card>

        {/* Bottom Section - "From here it's on us" */}
        <Card className="max-w-4xl mx-auto border shadow-lg bg-card/50 backdrop-blur-sm">
          <CardContent className="p-6 md:p-10 text-center">
            <div className="flex items-center justify-center gap-2 mb-4">
              <MessageSquare className="h-8 w-8 text-primary" />
              <h2 className="text-2xl md:text-3xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-primary to-primary/60">
                🤖 מכאן זה כבר עלינו
              </h2>
            </div>
            <p className="text-muted-foreground leading-relaxed text-base md:text-lg max-w-3xl mx-auto">
              אנחנו נאסוף את הלידים, נרכז את כל המידע במקום אחד,
              נענה בשמכם, נתזכר את הלקוחות שלכם בדיוק ברגע הנכון –
              כדי שכל ליד יהפוך להזדמנות אמיתית. 🎯
            </p>
          </CardContent>
        </Card>

        {/* Action Buttons */}
        <div className="max-w-4xl mx-auto mt-8 flex justify-center">
          <Button
            onClick={handleStart}
            size="lg"
            className="px-12 py-6 text-xl font-bold shadow-lg hover:shadow-xl transition-all"
          >
            בואו נתחיל! 🚀
          </Button>
        </div>
      </div>
    </div>
  );
};

export default Onboarding;
